# -*- coding: utf-8 -*-
"""vegetation_phenology.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10X_SqwHiVGidFGK_T6UlW_IdmIUKYPz-
"""

import ee
import geemap
import xarray as xr
import matplotlib.pyplot as plt

!pip install xee
import xee

ee.Authenticate()
ee.Initialize(project = 'ee-bastolashristi', opt_url = 'https://earthengine-highvolume.googleapis.com')

map = geemap.Map(basemap = 'SATELLITE', ee_initialize=False)
map

roi = map.draw_last_feature.geometry()
roi

ndvi = ee.ImageCollection("NOAA/CDR/VIIRS/NDVI/V1").select('NDVI','QA').filterDate('2023','2024')
ndvi

def cloud_mask(img):
  ndvi_img = img.select('NDVI').multiply(0.0001)
  qa_img = img.select('QA')
  cloud = qa_img.bitwiseAnd(1 << 1).neq(0)
  shadow = qa_img.bitwiseAnd(1 << 2).neq(0)
  mask = cloud.Or(shadow).Not()
  return ndvi_img.updateMask(mask).copyProperties(img, img.propertyNames())

ndvi_mask = ndvi.map(cloud_mask)
ndvi_mask

ds = xr.open_dataset(ndvi_mask, engine = 'ee', crs = 'EPSG:4326', scale = 0.1, geometry = roi)

ds

monthly = ds.resample(time = 'M').mean('time')

monthly

import matplotlib.pyplot as plt

monthly.NDVI.plot(
    x='lon',
    y='lat',
    col='time',
    col_wrap=4,
    figsize=(14, 10)
)

# Get the figure created by xarray
fig = plt.gcf()

fig.savefig("monthly_NDVI.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("monthly_NDVI.png")

!pip install netCDF4
import netCDF4

ds.to_netcdf('ndvi_daily.nc', engine='scipy')
print("Dataset saved to ndvi_daily.nc successfully using 'scipy' engine.")

!pip install dea_tools

import dea_tools.temporal

!pip install netCDF4
import netCDF4

import xarray as xr

ds = xr.open_dataset('ndvi_daily.nc')
print("Dataset opened successfully.")

!rm -f ndvi_daily.nc
print("Removed existing ndvi_daily.nc (if any).")

for var_name in ds.variables:
    if 'bounds' in ds[var_name].attrs:
        del ds[var_name].attrs['bounds']
ds.to_netcdf('ndvi_daily.nc', engine='scipy')
print("Dataset saved to ndvi_daily.nc successfully using 'scipy' engine.")

import xarray as xr
ds = xr.open_dataset('ndvi_daily.nc')
print("Dataset opened successfully.")
ds

phenology = dea_tools.temporal.xr_phenology(
    ds.NDVI,
    stats=['SOS', 'POS', 'EOS', 'Trough', 'vSOS', 'vPOS', 'vEOS', 'LOS', 'AOS', 'ROG', 'ROS'], method_sos='first', method_eos='last', verbose=True
)

phenology

import matplotlib.pyplot as plt

phenology.SOS.plot(
    x='lon',
    y='lat',
    robust=True,
    figsize=(8, 6)
)

# Capture the figure created by xarray
fig = plt.gcf()

fig.savefig("SOS_map.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("SOS_map.png")

import matplotlib.pyplot as plt

phenology.POS.plot(
    x='lon',
    y='lat',
    robust=True,
    figsize=(8, 6)
)

# Capture the figure created by xarray
fig = plt.gcf()

fig.savefig("POS_map.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("POS_map.png")

import matplotlib.pyplot as plt

phenology.vPOS.plot(
    x='lon',
    y='lat',
    robust=True,
    figsize=(8, 6)
)

# Capture the figure created by xarray
fig = plt.gcf()

fig.savefig("vPOS_map.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("vPOS_map.png")

import matplotlib.pyplot as plt

phenology.LOS.plot(
    x='lon',
    y='lat',
    robust=True,
    figsize=(8, 6)
)

# Capture the figure created by xarray
fig = plt.gcf()

fig.savefig("LOS_map.png", dpi=300, bbox_inches="tight")
plt.show()

from google.colab import files
files.download("LOS_map.png")